author: Chromium Authors <sky-dev@googlegroups.com>
dependencies:
  mojo: '>=0.0.1 <1.0.0'
  mojom: '>=0.0.4 <1.0.0'
  vector_math: '>=1.4.3 <2.0.0'
description: Dart files to support executing inside Sky.
homepage: https://github.com/domokit/mojo/tree/master/sky
name: sky
version: 0.0.13
